### ISSUE TITLE
Android Under 21 Api version not supported ?!

### ISSUE THREAD

**Issue by mohanadshaban** [oohyugi/sms_otp_auto_verify#6]
Flutter Version : 1.17.5 
Device : Emulator API 16 

After installing app the app crashes with StackTrace : 

> E/flutter ( 3736): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets
E/flutter ( 3736): 	at com.oohyugi.sms_otp_auto_verify.AppSignatureHelper.hash(AppSignatureHelper.kt:52)
E/flutter ( 3736): 	at com.oohyugi.sms_otp_auto_verify.AppSignatureHelper.getAppSignatures(AppSignatureHelper.kt:38)
E/flutter ( 3736): 	at com.oohyugi.sms_otp_auto_verify.SmsOtpAutoVerifyPlugin.onMethodCall(SmsOtpAutoVerifyPlugin.kt:33)
E/flutter ( 3736): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/flutter ( 3736): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter ( 3736): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/flutter ( 3736): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 3736): 	at android.os.MessageQueue.next(MessageQueue.java:125)
E/flutter ( 3736): 	at android.os.Looper.loop(Looper.java:124)
E/flutter ( 3736): 	at android.app.ActivityThread.main(ActivityThread.java:4745)
E/flutter ( 3736): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/flutter ( 3736): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/flutter ( 3736): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
E/flutter ( 3736): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/flutter ( 3736): 	at dalvik.system.NativeStart.main(Native Method)

if you can support to this low api i would appricate that .

Thanks !

**Comment by oohyugi** [comment]
Thanks for your report, i will check immediately
